### ISSUE TITLE
Does HTTP belong?

### ISSUE THREAD

**Issue by ggnbt** [kalisio/feathers-distributed#104]
@claustres  This project is very strong and nice. I am very happy.

I am testing Authentication on Api Gateway.
When accessing the service node from the feathers client via socket.io transport, it is checked, but when accessed from Insomnia over HTTP (fetch request from the browser), the data is returned without checking. Did I make a mistake? What should I do if it doesn't check naturally? Stop the HTTP server of service nodes?

I'm not using Docker. The examples are just run with nodejs. Lib codes was converted to CommonJS with Babel to link from typescript. Is there a reason for these?

Cote's document says "Deploying with Docker Cloud (**deprecated**)". What advice would you give about this? We are going to use it for long term work.

Thank you.

**Comment by ggnbt** [comment]
I sent a fetch request to the service node from the browser, but there was no response. Not even a mistake. 

I'm not using Docker. 2 source code ran with nodejs. Is there a reason here?

**Comment by ggnbt** [comment]
We also need to integrate swagger. What will be the solution to this?

**Comment by claustres** [comment]
I'm not sure what you mean by "checked", do you mean authenticated ? In the API gateway scenario your service nodes should not be publicly exposed as they are not "protected" using authentication, only the gateway should be exposed. So it is normal that you can reach your service directly using HTTP or Websocket.

Docker Cloud and Docker are different beasts. Docker Cloud is simply a Cloud service but Docker is the technology that started the containers. We are using Docker compose in the example because it is simple to use on a local machine even if for Cloud deployment Docker Swarm or Kubernetes are often used. However, Docker images remains the de facto standard for container images. We are deploying services using feathers-distributed and both technologies, it works fine.

**Comment by ggnbt** [comment]
Thank you for replying.

I'm sorry. My English is a little bad. "Checked" is used as "Authenticated". In general, I almost understand. :). Can you clarify the following?

Physical servers containing service nodes are generally located on the Internet with real addresses. We cannot share the authentication configuration (i.e. secret) with those servers. Therefore, the authentication scenario on the gateway is chosen. Users often access services through gateways.

But how to reuse authentication on the gateway when accessing the service node directly via HTTP or Websocket?.

**Comment by ggnbt** [comment]
![image](https://user-images.githubusercontent.com/33245352/185857046-4fb426f4-3c3c-4f59-99c2-04f63e23b3df.png)

**Comment by claustres** [comment]
In the gateway scenario the gateway should expose all services just like if they were local services. Thus you authenticate your client on the gateway then call services on the gateway as well. The fact your service node are publicly exposed on the internet, i.e. they have a public IP, does not mean the service is publicly exposed. For instance if you don't bind the port of your service on the host it will not be reachable so that there is no security concern here.

**Comment by ggnbt** [comment]
> In the gateway scenario the gateway should expose all services just like if they were local services. Thus you authenticate your client on the gateway then call services on the gateway as well. The fact your service node are publicly exposed on the internet, i.e. they have a public IP, does not mean the service is publicly exposed. For instance if you don't bind the port of your service on the host it will not be reachable so that there is no security concern here.

**Comment by ggnbt** [comment]
> In the gateway scenario the gateway should expose all services just like if they were local services. Thus you authenticate your client on the gateway then call services on the gateway as well. The fact your service node are publicly exposed on the internet, i.e. they have a public IP, does not mean the service is publicly exposed. For instance if you don't bind the port of your service on the host it will not be reachable so that there is no security concern here.

Thank you so much. I've been exploring Docker engine and Docker swarm for a while. I think I solved my problem with your help.

Sincerely
G. Ganbat
