### ISSUE TITLE
Question: New Version

### ISSUE THREAD

**Issue by boudydegeer** [kalisio/feathers-distributed#107]
hi @claustres , I just saw that you have updated the repository with alias for remote services, and functionality to not publish before service is ready. When do you think that you will deploy a release on that? I really need that functionality :P

Thanks for your great work. Keep it going.

**Comment by claustres** [comment]
Hi @boudydegeer we can plan to make a release soon if you are interested in. Could you have a look to the master branch and test if the new feature I documented [here](https://github.com/kalisio/feathers-distributed#remote-services) works for you ?

There is still a test failing concerning https://github.com/kalisio/feathers-distributed/issues/99, I am not sure yet exactly why so that I would like to tackle this before release. We'd also like to add a heartbeat feature to tackle https://github.com/kalisio/feathers-distributed/issues/80, the idea would be to republish services on a configurable regular basis (e.g. every minutes) not sure if it is useful for you.

Thanks.

**Comment by boudydegeer** [comment]
HI @claustres, sorry had no time until now to test it. Yes it works for me.

And those features you mention, I was thinking my self how to solve them. They would be very useful.

Let me know if I can help in something.

Thanks

**Comment by claustres** [comment]
Thanks for your help @boudydegeer might be useful you test the new `heartbeat` interval: https://github.com/kalisio/feathers-distributed#tips.

**Comment by claustres** [comment]
Even without feedback about this we made a new release to avoid some confusion (see https://github.com/kalisio/feathers-distributed/issues/110#issuecomment-1333328907).
