### ISSUE TITLE
fail requests to unresponsive nodes

### ISSUE THREAD

**Issue by Flofie** [kalisio/feathers-distributed#17]
Steps to reproduce:
2 services. - one gateway / one remote service
start both services. query some data throu the gateway from the service
http://gateway/service
now shutdown the service and query again
http://gateway/service

the request is stuck in infinte loop since the node where the service is running isnt there anymore but the remote service is still registerd on the gateway.

I tried something like
```javascript
class RemoteService {
  constructor (options) {
    this.remote = true;
    this.events = ['removed'];
  }
...
  this.requester.onRemoved = x => {
     this.emit('removed', `/${this.path}`);
  };
```

```javascript
app.use(serviceDescriptor.path, new _service.RemoteService(serviceDescriptor));
   debug('Registered remote service on path ' + serviceDescriptor.path);
   app.service(serviceDescriptor.path).on('removed', path => {
      app._router.stack = app._router.stack.filter(f =>
         f.route && f.route.path ? !f.route.path.startsWith(path) : true
      );
   });
```

This works a expected. The problem is now if the remote node with the service comes back the services isnt reregistered since the feathersapp still has the remote service with the service.
Do you have an idea how to reregister the service? Or maybe the best way would be to remove the feathers service of the service but Im not sure if this is possible.

**Comment by claustres** [comment]
Can't understand why an infinite loop appears. Anyway IMHO this is the responsability of cotejs to handle this kind of use cases since it manages service discovery: if there is no responder to handle the request anymore it should simply send a timeout to the requester.. 

Your approach is still related to express only and the fact it does not provide an easy way to remove middleware. However it will fail in a distributed environment where the service can be duplicated N times, we should at least perform the removal only when all duplicated services are down. Even in this case this should not be automated since in a fault-tolerant mode all services might crash at some point then pop again a couple of seconds/minutes after.

Probably need more investigation to handle smoothly dynamic service dead and resurrection.

**Comment by claustres** [comment]
I wonder if this is not related to https://github.com/dashersw/cote/issues/123. Maybe an upgrade could make it work better.

**Comment by Flofie** [comment]
Uh, that sounds promising.
On hacky solution I justed tried is

 ```javascript
// Perform requests to other nodes
find(params) {
    debug('Requesting find() remote service on path ' + this.path, params);
    return new Promise((resolve, reject) => {
      this.requester.send({ type: 'find', params }).then(result => {
        debug('Successfully find() remote service on path ' + this.path);
        resolve(result);
      });
      setTimeout(reject, 5000);
   });
}

but even this rejection isnt rejecting the intial request. Very strange.
```

**Comment by claustres** [comment]
With your trick you are killing the feathers-distributed promise but `this.requester.send()` is an internal promise of cotejs that cannot be resolved except in cotejs itself, nothing we can do on our side.
