### ISSUE TITLE
Performance overhead with a large number of services

### ISSUE THREAD

**Issue by claustres** [kalisio/feathers-distributed#48]
When reaching a large number of services (> 100) you can experience some performance issues like CPU load for message processing or network bandwidth consumption. Now we mitigate this by increasing the different intervals (hello/check messages) in the cote configuration. However this might not work with a large number of services. Refer to related [cote issue](https://github.com/dashersw/cote/issues/210).

We should probably manage all services methods using a single or limited set of requesters/responders and similarly service events using a single or limited set of publishers/subscribers.

**Comment by aikar** [comment]
If @dasherws pulls my PR to node-discover in once its merged at https://github.com/wankdanker/node-discover/pull/39/files - this should at least greatly help reduce CPU cost in cote.

**Comment by dashersw** [comment]
@aikar have you run a benchmark on how much this saves performance? If we have concrete results, I'd be happy to review it and merge it to my branch, without waiting for the merge to the original repo.

**Comment by aikar** [comment]
benchmarks no, but avoiding synchronous cpu intensive encryption and synchronous cpu intensive serialization logic blocking the node.js event loop is overall pretty clear it will be an improvement.

@claustres identified this code is the problem here: https://cotejs.slack.com/archives/C06MER4NT/p1570175857015100

So this PR simply skips even running this code all together.
