### ISSUE TITLE
Working app or example of per-service authentication?

### ISSUE THREAD

**Issue by corepay** [kalisio/feathers-distributed#71]
Hi,

Any examples app or more information on how to do the per-service authentication using feathers-distributed?  

I can't reason the test file linked as a reference into a working model.  Would help a lot to see an app in action.

Thanks...

**Comment by claustres** [comment]
Hi, not sure what you mean by per-service authentication. You can find a working sample in the [example](https://github.com/kalisio/feathers-distributed/tree/master/example) folder.

There are usually two use cases for authentication as explained [here](https://github.com/kalisio/feathers-distributed#authentication). Indeed, this module exposes services owned by some apps to others apps but it does not really manage authentication, it is done the "feathers way" using a hook. If all apps are publicly exposed then you should register the authentication hook on each app (distributed use case). If only a single app is publicly exposed while others are only "backend apps" not visible to the users you should only register the hook on the exposed app (gateway use case). 

As often in feathers you can setup the hook on a per-service basis or at application level.

**Comment by corepay** [comment]
Hi Luc,

Yes, referring to the distributed use case.

Here is my goal I thought your library could help me accomplish.

Auth Server - fresh install authentication, user/users entity created and `feathers-distributed` dependency installed:
```
// app.js
const distribution = require('@kalisio/feathers-distributed');
...
app.configure(
  distribution({
    remoteServices: ['customers', 'invoices']
  })
)
```

Ok - here is where I am not clear

1.  When generating a new feathers app for a customer-server do I select Y for authentication to create the user entity again in that app?  <-- don't think so this defeats the purpose of separation of concerns to have users service here and on auth server and have to duplicate the models, etc.

2.  If I generate a new customer-server app with N on the authentication I get the app without a db reference and no user entity.  I then generated a feathers service to create a `/customers` endpoint and data model which also creates my sequelize connection <--- assuming so far so good.

Trying #2 above I then install the feathers-distributed and feathers-authentication dependencies through Yarn and add the following to `app.js`

```
const distribution = require('@kalisio/feathers-distributed');
...
app.configure(distribution());
```

Now what?  I don't get the instruction -  **register the authentication hook.** 

Does this mean to install the featehrs authentication library and add `app.use` in app.js and/or create an authentication.js and update the default.json with authentication config params....or do I import the authentication package in my `/customers` hooks and then an `authenticate('jwt')` before hook?  

Was hoping you could point me to a project that did distributed feathers so I check it out and reason the code.  I searched github but didn't find anything similar.

I've been using feathers on several projects successfully and am familiar with it but the auth strategies leaves me confused and frustrated...

**Comment by claustres** [comment]
You are right about separation of concerns and that's the reason why usually the gateway scenario is more easy to implement. In your case the gateway would be the auth server, it owns the authentication service to generate JWTs and apply the authenticate hook on each remote service like [this](https://github.com/kalisio/feathers-distributed#api-gateway). In that case you access your customer service from the auth server with a JWT retrieved after a local authentication on it as usual.

Now if you really want to make your customer service to be distributed and reachable from any server/app, then you have to "share" the user service among your apps. There are two options:
- you create a user service in each app as usual but reference the same model (ie DB)
- your auth server distributes the user service to others apps

In that case you add the authenticate hook on each app/service as usual.

The same might apply to the authentication service, you can have it only available in your auth server so that clients first authenticate on it then use the retrieved JWT to call services on others apps or you can create the authentication service on each app so that clients can authenticate on any app.

I'm afraid we don't yet have any real-world working example of this kind of distribution, although we actually do that in our [tests](https://github.com/kalisio/feathers-distributed/blob/master/test/index.test.js#L525). It would be probably useful to create a distributed system, let us know if you are trying to achieve this.

**Comment by corepay** [comment]
Thank Luc,

I'm giving it some focus now.  Will let you know if I have success.

**Comment by corepay** [comment]
Luc, can a feathers-distributed micro-services plug into Kaabah without a lot of configuration?  Looking at it now...tried swarm/terraform a while back liked what I saw.

**Comment by claustres** [comment]
Hope this will help https://github.com/kalisio/feathers-distributed/blob/master/README.md#cloud-deployment.

**Comment by corepay** [comment]
Thanks - yes helped a lot...rolled my own using your pattern.  Closing now to clear your issues up....
